# Created by Yilin Xu (1201608) from group 45 of COMP90024 2021 Semester 1 Assignment 2 at the University of Melbourne

# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: web-vol
    vol_size: 50
  - vol_name: harvester-1-vol
    vol_size: 50
  - vol_name: harvester-2-vol
    vol_size: 50
  - vol_name: harvester-3-vol
    vol_size: 50

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb
    description: "Security group for couchdb primary port"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5987
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb cluster
    description: "Security group for couchdb cluster"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb erlang
    description: "Security group for couchdb erlang"
    protocol: tcp
    port_range_min: 4200
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: webserver
    instance_key_name: cloud
    instance_flavor: uom.mse.2c9g
    volumes: ['web-vol']
  - name: harvesterserver-1
    instance_key_name: cloud
    instance_flavor: uom.mse.2c9g
    volumes: ['harvester-1-vol']
  - name: harvesterserver-2
    instance_key_name: cloud
    instance_flavor: uom.mse.2c9g
    volumes: ['harvester-2-vol']
  - name: harvesterserver-3
    instance_key_name: cloud
    instance_flavor: uom.mse.1c4g
    volumes: ['harvester-3-vol']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
