---

# Created by Yilin Xu (1201608) from group 45 of COMP90024 2021 Semester 1 Assignment 2 at the University of Melbourne

- name: Install Nginx
  become: yes
  apt:
    name: ['nginx']
    state: latest
    update_cache: yes

- name: Add location of IP.txt
  become: yes
  lineinfile:
      dest: /etc/nginx/sites-enabled/default
      insertafter: 'server {'
      line: "location /ip {
                alias /home/ubuntu/IP.txt;
        }
        location / {
                try_files $uri$args $uri$args/ /index.html;
        }"