---

# Created by Yilin Xu (1201608) from group 45 of COMP90024 2021 Semester 1 Assignment 2 at the University of Melbourne

- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes

- name: Update pip
  pip:
    name: ['pip']
    state: latest

- name: Install openstacksdk
  pip:
    name: ['openstacksdk==0.52']
    state: latest
