# Created by Yilin Xu (1201608) from group 45 of COMP90024 2021 Semester 1 Assignment 2 at the University of Melbourne

- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- hosts: webserver, harvesterserver
  become: yes
  roles:
    - role: config-common
    - role: config-couchdb

- hosts: localhost
  tasks:
  - name: Install couchdb cluster
    shell: | 
      bash ./install-dbcluster.sh
  

- hosts: webserver
  become: yes
  roles:
    - role: config-web

- hosts: harvesterserver
  become: yes
  roles:
    - role: config-harvester

- hosts: localhost
  tasks:
  - name: Upload AURIN Dataset to CouchDB
    shell: | 
      python3 /home/ubuntu/comp90024/harvester/uploader.py
  - name: Create views in CouchDB
    shell: | 
      Bash /home/ubuntu/comp90024/ansible/create-views.sh

- hosts: harvesterserver
  tasks:
  - name: Run harvesters
    shell: | 
      nohup python3 /home/ubuntu/comp90024/harvester/harvester.py &
