- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- hosts: webserver, harvesterserver
  become: yes
  roles:
    - role: config-common
    - role: config-couchdb
    - role: config-dbcluster

- hosts: webserver
  become: yes
  roles:
    - role: config-web

- hosts: harvesterserver
  become: yes
  roles:
    - role: config-harvester
