---

- name: Add couchdb key
  become: yes
  shell: |
    curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc | sudo apt-key add -

- name: Add couchdb repository
  become: yes
  shell: |
    echo "deb https://apache.bintray.com/couchdb-deb focal main" | sudo tee -a /etc/apt/sources.list

- name: Copy installation script from local to remote
  become: yes
  copy:
    src: /home/ubuntu/ansible/install-couchdb.sh
    dest: /home/ubuntu/install-couchdb.sh
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Change installation script permissions
  become: yes
  shell: |
    chmod 777 /home/ubuntu/install-couchdb.sh

- name: Install couchdb
  become: yes
  command: sh /home/ubuntu/install-couchdb.sh
